language: java
sudo: false
jdk:
  - oraclejdk8
script: "mvn cobertura:cobertura"
before_install:
  - "mvn clean"
install:
  - "mvn package -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  - $HOME/.m2
