language: java
sudo: false
jdk:
  - oraclejdk8
script: "mvn cobertura:cobertura"
before_install:
  - "export MAVEN_OPTS=-Xms1024m -Xmx1G -XX:PermSize=1024m -noverify""
install:
  - "mvn clean && mvn package -DskipTests=true"
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  - $HOME/.m2
